### ISSUE TITLE
Lecture4 : BlackJack example corrections required in code

### ISSUE THREAD

**Issue by vjg28** [dalmia/David-Silver-Reinforcement-learning#2]
The codes Blackjack_playground.ipynb and model_free_prediction both contains a part of code in the starting
>>import sys
>>if "../" not in sys.path:
..    sys.path.append("../") 
>>from lib.envs.blackjack import BlackjackEnv
>>from lib import plotting

>>env = BlackjackEnv()

This part of the code gives error "ImportError: "lib" not found". This is because Denny Britz used a different file structure for module placement. The correct version for any general user should be:
Step1: Add plotting.py file from "Denny Britz" library in the same folder as the codes.
Step2 : corrections in code:

>>import gym
>>from plotting import *

>>env=gym.make('Blackjack-v0')

**Comment by dalmia** [comment]
@vjg28 Yes, that's true. But there are still a few environments that are present in `lib`, that are not yet released officially under `gym`. To maintain consistency, I have kept it in the same way as presented originally by Denny Britz.

**Comment by vjg28** [comment]
Yeah  OK.  I got that point after following algorithms in environments like windy_gridworld that were not by default present in gym. They must be added to the gym library to use them through gym. 
Thanks for your response.
